### ISSUE TITLE
Should this not be an empty string instead of 0x00 as it was in the example from earlier in the lesson?

### ISSUE THREAD

**Issue by gimballock** [chaincodelabs/bitcoin-tx-tutorial#16]
https://github.com/chaincodelabs/bitcoin-tx-tutorial/blob/d842ebfc0608a890c483ea53f59f9bdd01e042f9/chapter1-legacy/p2pkh.ipynb#L847

**Comment by DariusParvin** [comment]
Hi @gimballock, great observation. Yes that is an error and should be an empty string. If you like you can open a PR to correct it (and anywhere else if you see it), or i'll get to it this weekend. Thanks!
