### ISSUE TITLE
Wrong Addresses Prefixes on ~/bitcoin-tx-tutorial/appendix/addresses.ipynb

### ISSUE THREAD

**Issue by MPins** [chaincodelabs/bitcoin-tx-tutorial#31]
There is an error on the testnet/regtest prefixes

Base58 address prefixes

These address formats not only encode the scriptPubKey for the output, but they also encode a prefix that specifies which network (mainnet/testnet) the output is intended for. Other cryptocurrencies based on bitcoin forks (e.g. litecoin or zcash) will use different prefix values to indicate which cryptocurrency the output is intended for. If a wallet implementation doesn't check that the prefix matches with the type of transaction being created, the wallet user may end up creating a transaction that for a different cryptocurrency than the one the user is intending to use.

Here are some commonly used bitcoin address prefixes:

    Base58
        Mainnet
            P2PKH - 0x00
            P2SH - 0x05
        Testnet/Regtest
            P2PKH - 0x00 <------ 0x6F
            P2SH - 0x05   <------- 0xC4

**Comment by DariusParvin** [comment]
Hi @MPins thanks a lot for spotting this! I will create a PR for this on the weekend, or if you want, feel free to open one yourself.

**Comment by MPins** [comment]
Hello @DariusParvin, congratulations for the amazing work you have been done here! It will be a pleasure creating the PR. I‘ll do it later today.
