### ISSUE TITLE
JSON value of type string is not of expected type array on `testmempoolaccept'

### ISSUE THREAD

**Issue by MPins** [chaincodelabs/bitcoin-tx-tutorial#33]
---------------------------------------------------------------------------
JSONRPCException                          Traceback (most recent call last)
Cell In[15], line 3
      1 # Do not brodcast, try changing it first 
      2 node.sendrawtransaction(signed_tx.hex())
----> 3 node.testmempoolaccept(signed_tx.hex())

File ~/bitcoin/test/functional/test_framework/coverage.py:49, in AuthServiceProxyWrapper.__call__(self, *args, **kwargs)
     43 def __call__(self, *args, **kwargs):
     44     """
     45     Delegates to AuthServiceProxy, then writes the particular RPC method
     46     called to a file.
     47 
     48     """
---> 49     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
     50     self._log_call()
     51     return return_val

File ~/bitcoin/test/functional/test_framework/authproxy.py:144, in AuthServiceProxy.__call__(self, *args, **argsn)
    142 response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
    143 if response['error'] is not None:
--> 144     raise JSONRPCException(response['error'], status)
    145 elif 'result' not in response:
    146     raise JSONRPCException({
    147         'code': -343, 'message': 'missing JSON-RPC result'}, status)

JSONRPCException: Wrong type passed:
{
    "Position 1 (rawtxs)": "JSON value of type string is not of expected type array"
} (-3)

**Comment by MPins** [comment]
I can investigate further if you think it is worth it.

**Comment by DariusParvin** [comment]
hey @MPins thanks for posting this. Could you provide some more context around how to reproduce this issue? I think you're the first so it's unclear if it's something to do with your setup or a bug in the code. This kind of bug seems unexpected. Could you also include what version of bitcoin core you're running in case that's the issue too.

**Comment by MPins** [comment]
I 'm just following the Chapter1-legacy -> Maleability of ECDSA  and before broadcast the transaction (on regtest mode) I tried the `testmempoolaccept` where I got the error.

I'm running Bitcoin Core Version: 240001 (/Satoshi:24.0.1(testnode0)/).

**Comment by DariusParvin** [comment]
thanks a lot @MPins , that context helps. And yes i see the issue now. That command is using `testmempoolaccept` incorrectly:

`node.testmempoolaccept(signed_tx.hex())` , passing in the tx hex as just a raw string, when it should be in an array e.g.:

`node.testmempoolaccept(rawtxs=[signed_tx.hex()])`. 

If you have the chance can you try that command instead and confirm it works? If so, feel free to open a PR to fix it, or i can get round to it this weekend

**Comment by MPins** [comment]
It works perfectly!
